# Generated by Django 4.2.10 on 2024-03-03 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cedula",
                    models.CharField(max_length=10, unique=True, verbose_name="Cédula"),
                ),
                (
                    "primer_nombre",
                    models.CharField(max_length=20, verbose_name="Primer Nombre"),
                ),
                (
                    "segundo_nombre",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Segundo Nombre",
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("H", "Hombre"), ("M", "Mujer")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                ("edad", models.PositiveIntegerField(verbose_name="Edad")),
                (
                    "email",
                    models.EmailField(
                        max_length=30,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=30, verbose_name="Dirección"),
                ),
            ],
        ),
    ]
